name: ECR Scan Image
description: Scan an image in ECR and fail if vulnerabilities are found
inputs:
  repository:
    description: ECR repository, eg myorg/myimage.
    required: true
  tag:
    description: Image tag to scan.
    required: true
  fail_threshold:
    description: >
      Fail if any vulnerabilities equal to or over this severity level are detected. Valid values: critical, high, medium, low, informational.
    default: medium
outputs:
  critical:
    description: Number of critical vulnerabilities detected.
  high:
    description: Number of high vulnerabilities detected.
  medium:
    description: Number of medium vulnerabilities detected.
  low:
    description: Number of low vulnerabilities detected.
  informational:
    description: Number of informational vulnerabilities detected.
  unknown:
    description: Number of unknown severity vulnerabilities detected.
  total:
    description: Total number of vulnerabilities detected.
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "camera"
  color: "orange"
